version: '2'
services:
  ts_gateway_ang-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/TS_Gateway_ANG/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=TS_Gateway_ANG
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
