export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  VENDEUR = 'ROLE_VENDEUR',
  ADMIN_COMMERCIAL = 'ROLE_ADMIN_COMMERCIAL',
  COMMERCIAL = 'ROLE_COMMERCIAL',
  MAGASINIER = 'ROLE_MAGASINIER',
  CLIENT = 'ROLE_CLIENT',
  RPV_CLIENT = 'ROLE_RPV_CLIENT',
  CHEF_PARK = 'ROLE_CHEF_PARK',
}
